from pydantic import BaseModel, Field
from typing import Optional, Dict, Any

class UploadResponse(BaseModel):
    status: str = Field(..., description="Status of the upload processing, e.g., 'success' or 'error'")
    filename: str = Field(..., description="Original name of the uploaded document")
    extracted_text: str = Field(..., description="Extracted raw text content from the document")
    ai_response: str = Field(..., description="Plain-language explanation and action items generated by Gemini")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Additional document processing metadata")

class ErrorResponse(BaseModel):
    status: str = "error"
    error: str = Field(..., description="Detailed error description")
    code: Optional[int] = Field(500, description="HTTP or error code")

class HealthResponse(BaseModel):
    status: str = "ok"
    service: str = "CivicOps Backend"
    gemini_configured: bool
    adk_status: Dict[str, Any]
